export const EXPLOSIVE_STATUS_CHANGED = 'EXPLOSIVE_STATUS_CHANGED';
export const MELEE_STATUS_CHANGED = 'MELEE_STATUS_CHANGED';
export const GUNS_STATUS_CHANGED = 'GUNS_STATUS_CHANGED';
export const THROWING_STATUS_CHANGED = 'THROWING_STATUS_CHANGED';
export const SAM_STATUS_CHANGED = 'SAM_STATUS_CHANGED';
